services:
  dev:
    build: ./.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/com.docker.devenvironments.code/build-first-website-with-python/app

  python:
    build: 
      context: ./
      target: dev
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/local/app
