services:
  dev:
    build: ./.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/com.docker.devenvironments.code

  python:
    build: 
      context: ./
      target: dev
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/local/app
