services:
  workspace:
    build: ./.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src:/com.docker.devenvironments.code/build-first-website-with-python/src

  python:
    build: 
      context: ./
      target: dev
    ports:
      - 5000:5000
    volumes:
      - ./src:/usr/local/app
